services:
  - type: web
    name: tracksmart-backend
    runtime: node
    plan: free
    buildCommand: cd /opt/render/project/server && npm install && npm run build
    startCommand: cd /opt/render/project/server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        scope: run
        value: https://tracksmart-2026.vercel.app
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        scope: run
        value: ./firebase-service-account.json
